services:
  postgres:
    environment:
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  rabbitMq:
    ports:
      - "5672:5672"
      - "15672:15672"